In [2]:
import tensorflow as tf

/home/cuongpc/ENV/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/home/cuongpc/ENV/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


1.Set dimensions of the input images

In [3]:
batch_size=128
no_classes=10
epochs=2
image_height,image_width=28,28

2.Load the data from disk to memory the keras

In [4]:
(x_train,y_train),(x_test,y_test)=tf.keras.datasets.mnist.load_data()

3.Reshape the vector into an image format,and define the input dimension for the convolution
using the code given

In [5]:
x_train=x_train.reshape(x_train.shape[0],image_height,image_width,1)
x_test=x_test.reshape(x_test.shape[0],image_height,image_width,1)
input_shape=(image_height,image_width,1)

4.Convert the data type to float as follows

In [6]:
x_train=x_train.astype('float32')
x_test=x_test.astype('float32')

5.Normalize the data by subtracting the mean of the data

In [7]:
x_train/=255
x_test/=255

6.Convert the categorical labels to one-shot encoding:

In [8]:
y_train=tf.keras.utils.to_categorical(y_train,no_classes)
y_test=tf.keras.utils.to_categorical(y_test,no_classes)
print(y_train)
print(y_test)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]
[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [9]:
def simple_cnn(input_shape):
    model=tf.keras.models.Sequential()
    model.add(tf.keras.layers.Conv2D(
        filters=64,
        kernel_size=(3,3),
        activation='relu',
        input_shape=input_shape
    ))
    model.add(tf.keras.layers.Conv2D(
        filters=128,
        kernel_size=(3,3),
        activation='relu'
    ))
    model.add(tf.keras.layers.MaxPooling2D(pool_size=(2,2)))
    model.add(tf.keras.layers.Dropout(rate=0.3))
    model.add(tf.keras.layers.Flatten())
    model.add(tf.keras.layers.Dense(units=1024,activation='relu'))
    model.add(tf.keras.layers.Dropout(rate=0.3))
    model.add(tf.keras.layers.Dense(units=no_classes,activation='softmax'))
    model.compile(loss=tf.keras.losses.categorical_crossentropy,optimizer=tf.keras.optimizers.Adam(),
    metrics=['accuracy'])
    return model
    

In [ ]:
simple_cnn_model=simple_cnn(input_shape)
simple_cnn_model.fit(x_train,y_train,batch_size,epochs,(x_test,y_test))
train_loss,train_accuracy=simple_cnn_model.evaluate(x_train,y_train,verbose=0)

Epoch 1/2


In [ ]:
print('Train data loss:',train_loss)
print("Train data accuracy:",train_accuracy)

In [ ]:
test_lost,test_accuracy=simple_cnn_model.evaluate(
    x_test,y_test,verbose=0)

In [ ]:
print('Test data loss:',test_loss)
print("Test data accuracy:",test_accuracy)